server:
  port: 8008
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.28.101:3306/gulimall_ums?useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.28.101:8848
  application:
    name: gulimall-member
  thymeleaf:
    cache: false
  session:
    store-type: redis
  redis:
    host: 192.168.28.101
    port: 6379

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto