server:
  port: 9099
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.28.101:8848
  application:
    name: gulimall-order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.28.101:3306/gulimall_oms?useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  rabbitmq:
    host: 192.168.28.101
    port: 5672
    virtual-host: /
    #确认机制 一般不使用, 这是抵达服务器确认ack
    publisher-confirms: true
    # 抵达queue时，确认ack
    publisher-returns: true
    # 抵达队列，异步回调ack
    template:
      mandatory: true
    # 手动确认收到消息  消费端 ack
    listener:
      simple:
        acknowledge-mode: manual
  session:
    store-type: redis
  redis:
    port: 6379
    host: 192.168.28.101
  thymeleaf:
    cache: false
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
