spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.28.101:8848
  redis:
    host: 192.168.28.101
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8